const $=id=>document.getElementById(id);let jobId=null,rows=[],timer=null,started=0,eventOffset=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function kws(){return $('keywords').value.split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean)}
function render(){const q=($('filter').dataset.q||'').toLowerCase();$('keywordList').innerHTML=kws().map(k=>`<div class="keyword-row">${esc(k)}</div>`).join('');$('results').innerHTML=rows.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q)).map(r=>`<tr><td>${esc(r.email)}</td><td>${esc(r.title)}</td><td data-url="${esc(r.source_url)}">${esc(r.source_url)}</td><td>${r.score||0}</td><td>${esc(r.method||'regex')}</td></tr>`).join('')}
function modal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').classList.add('open')}
$('modal').onclick=e=>{if(e.target.id==='modal')$('modal').classList.remove('open')};$('keywords').oninput=render;$('clearKeywords').onclick=()=>{$('keywords').value='';render()};$('addKeyword').onclick=()=>{const v=prompt('Keyword');if(v)$('keywords').value+=($('keywords').value?'\n':'')+v;render()};
async function start(){const url=$('url').value.trim();if(!/^https?:\/\/[^\s]+$/i.test(url))return modal('Invalid URL','Enter a public or authorized http:// or https:// URL.');const output=prompt('Local output file path','emails.csv')||'emails.csv';$('start').disabled=true;rows=[];eventOffset=0;render();started=Date.now();timer=setInterval(()=>{$('elapsed').textContent=new Date(Date.now()-started).toISOString().slice(11,19)},500);const body={url,keywords:kws(),output,max_pages:+$('pages').value,max_depth:+$('depth').value,delay:.5,timeout:10,max_bytes:2000000};try{const r=await fetch('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error);jobId=j.id;poll()}catch(e){$('status').textContent=e.message;$('start').disabled=false;clearInterval(timer)}}
async function poll(){try{const j=await (await fetch('/api/jobs/'+jobId)).json(),p=j.progress||{};const ev=await (await fetch('/api/jobs/'+jobId+'/events',{headers:{'X-Event-Offset':String(eventOffset)}})).json();ev.events.forEach(e=>{eventOffset++;if(e.event==='contact'&&!rows.some(r=>r.email===e.email))rows.push(e)});render();const max=+(p.max_pages||$('pages').value),page=+(p.pages||0),pct=Math.min(100,max?page/max*100:0);$('overall').style.width=pct+'%';$('pct').textContent=pct.toFixed(1)+'%';$('queueText').textContent=(p.queued||0)+' URLs';$('queueBar').style.width=Math.min(100,(p.queued||0)/Math.max(1,max)*100)+'%';$('emails').textContent=p.emails||0;$('parsed').textContent=page;$('queued').textContent=p.queued||0;$('urls').textContent=p.discovered_urls||0;$('errors').textContent=p.errors||0;$('domains').textContent=p.discovered_urls?1:0;$('status').textContent=(p.event||j.state)+(p.url?' — '+p.url:'');if(j.state==='done'||j.state==='error'||j.state==='cancelled'){clearInterval(timer);$('start').disabled=false;$('status').textContent=j.state==='done'?'Completed — output saved to '+j.output:j.state;return}setTimeout(poll,700)}catch(e){setTimeout(poll,1500)}}
$('start').onclick=start;$('clearGrid').onclick=()=>{rows=[];render()};$('filter').onclick=()=>{const q=prompt('Filter results','');$('filter').dataset.q=q||'';render()};$('validate').onclick=()=>modal('Validation',`Valid addresses: <b>${rows.filter(r=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(r.email)).length}</b><br>Total rows: ${rows.length}`);$('save').onclick=()=>{const csv=['email,source_url,title,score,method',...rows.map(r=>[r.email,r.source_url,r.title,r.score,r.method].map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='webcontactcrawler-results.csv';a.click()};
$('settings').onclick=()=>modal('Settings','Set URL, depth, page budget and local output when starting a crawl. Robots-aware, same-domain and rate-limited crawling remains enabled.');$('help').onclick=()=>modal('Help','Enter a public/authorized URL and optional keywords, then press Search Now. Use Import for TXT/CSV. Progress and counters update while a job runs.');$('about').onclick=()=>modal('About','WebContactCrawler — bounded public-web email extraction with provenance and live telemetry.');$('helpKeywords').onclick=()=>modal('Keyword Help','Use one keyword per line. Keywords affect relevance scoring and do not authorize private access.');$('quit').onclick=()=>window.close();$('clearHistory').onclick=()=>{$('status').textContent='Session history cleared.'};
$('importFile').onclick=()=>$('fileInput').click();$('fileInput').onchange=async()=>{const f=$('fileInput').files[0];if(!f)return;const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.name,content:await f.text()})}),d=await r.json();rows=d.emails.map(email=>({email,title:'Imported',source_url:'',score:0,method:'file-import'}));render();$('status').textContent=`Imported ${d.count} unique email addresses.`};
document.addEventListener('dblclick',e=>{const c=e.target.closest('[data-url]');if(c?.dataset.url)window.open(c.dataset.url,'_blank','noopener')});render();
